export const MOVE_PLAYER_ONE_SUCCESS = 'MOVE_PLAYER_ONE_SUCCESS'

export const MOVE_PLAYER_TWO_SUCCESS = 'MOVE_PLAYER_TWO_SUCCESS'

export const CHANGE_CURRENT_PLAYER_SUCCESS = 'CHANGE_CURRENT_PLAYER_SUCCESS'
