export const LOAD_HOME_DATA_SUCCESS = 'LOAD_HOME_DATA_SUCCESS'

export const CLEAR_HOME_DATA_SUCCESS = 'CLEAR_HOME_DATA_SUCCESS'

export const LOAD_NEWS_DATA_SUCCESS = "LOAD_NEWS_DATA_SUCCESS"

export const CLEAR_NEWS_DATA_SUCCESS = "CLEAR_NEWS_DATA_SUCCESS"
